// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var CountrySelect = require("./CountrySelect.bs.js");
var Client = require("react-dom/client");

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  var onChange = function (e) {
    console.log("Selected value:" + e);
  };
  root.render(React.createElement(React.Fragment, undefined, React.createElement(CountrySelect.make, {
                className: "x1",
                country: "us",
                onChange: onChange
              })));
}

/* rootElement Not a pure module */
